name: Added Parameters

on:
  workflow_run:
    workflows: ["notify the main workflow"]
    types:
      - completed

jobs:
  adding-parameters:
    runs-on: ubuntu-latest
    name: Added parameters to the workflow
    steps:
      - name: Added parameters
        id: Parameters
        uses: venkat785/java-integrate@main
        with:
          owner: "venkat785"
          repository: "java-integrate"
          base: "main"
          head: "jsdev"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Use the output from the `Parameters` step
      - name: Get the output
        run: echo "The output was ${{ steps.Parameters.outputs.output }}"
