name: testing4

on:
  workflow_run:
    workflows: ["testing3"]
    types:
      - completed

jobs:
  calling-another-github-action:
    runs-on: ubuntu-latest
    steps:
      - name: calling workflow
        run: echo "testyaml4"
      - name: calling workflow2
        run: echo "nextjob is test5"
