name: testing2

on:
  workflow_run:
    workflows: ["Added Parameters"]
    types:
      - completed

jobs:
  calling-another-github-action:
    runs-on: ubuntu-latest
    steps:
      - name: calling workflow
        run: echo "testyaml2"
      - name: calling workflow2
        run: echo "nextjob is test3"
