name: notify the main workflow

on: push

jobs:
  calling-another-github-action:
    runs-on: ubuntu-latest
    steps:
      - name: calling workflow
        run: echo "parameters job will run"
      - name: shell commands
        run: |
          node -v
          npm -v
