name: testing5

on:
  workflow_run:
    workflows: ["testing4"]
    types:
      - completed

jobs:
  calling-another-github-action:
    runs-on: ubuntu-latest
    steps:
      - name: calling workflow
        run: echo "all workfl0ws are done"
      - name: calling workflow2
        run: echo "theres no other jobs
